// Google OAuth client configuration
const GOOGLE_CLIENT_ID = process.env.REACT_APP_GOOGLE_CLIENT_ID;
const GOOGLE_CLIENT_SECRET = process.env.REACT_APP_GOOGLE_CLIENT_SECRET;

export { GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET };